# localization module: localization_2d,...
string module_name
# environment id: lab_1,...
string environment
# map name: lab_1_nav_1,...
string map_name
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
